version: '3.7'
services:
  kaldi:
    image: "danijel3/kaldi-online-tcp:aspire"
    restart: unless-stopped
  web:
    build: ./web
    image: "ceylont/kaldi-webrtc"
    restart: unless-stopped
    volumes:
      - ./servers.json:/server/servers.json

    